/********************************************************************
 *   This C program was generated by spl2c, the Shakespeare to C    *
 *          converter by Jon Åslund and Karl Hasselström.           *
 ********************************************************************/

/* libspl definitions and function prototypes */
#include <spl.h>

int main(void)
{
  /******************************************************************
   * HELLO WORLD                                                    *
   ******************************************************************/
  
  CHARACTER *benvolio;                    /* That one guy from Romeo and Juliet */
  
  int comp1, comp2;
  
  global_initialize();
  
  benvolio = initialize_character("Benvolio");
  
  act_i:                                  /* Greetings to the Universe */
  
  act_i_scene_i:                          /* The greeting of the world */
  
  enter_scene(8, benvolio);
  
  activate_character(14, benvolio);
  assign(12, second_person, int_mul(11, 2*2*1, 2*2*2*1));
  char_output(12, second_person);
  
  exit_scene_all(14);
  
  return 0;
}
